version: '3.8'
services:
  link-converter:
    build: .
    image: linkconverter
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    ports:
      - 8080:8080
    depends_on:
      elasticsearch:
        condition: service_healthy
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    ports:
      - 9200:9200
    environment:
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
      - 'discovery.type=single-node'
    healthcheck:
      test: curl -u elastic:elastic -s -f elasticsearch:9200/_cat/health >/dev/null || exit 1
      interval: 6s
      timeout: 5s
      retries: 50